### ISSUE TITLE
Support packed torrents in some way?

### ISSUE THREAD

**Issue by fryfrog** [l3uddz/tqm#44]
Would it be possible to detect packed torrents in some way? I'd like to set those to a different ratio so they're removed sooner.

**Comment by fryfrog** [comment]
Ah, nice! As a big dummy... how could I have figured that out on my own?

**Comment by l3uddz** [comment]
The documentation is not great agreed 😜 .

The language definition the filtering system uses can be viewed at: https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md

The Torrent struct that the filters evaluate against can also be viewed at: https://github.com/l3uddz/tqm/blob/master/config/torrent.go

One day I will get around to writing a wiki or something!

**Comment by fryfrog** [comment]
For any future readers, we ended up with:

```
count (Files, {# matches "(?i)\\.(rar|r\\d\\d)$"}) > 3
```

The `r\d\d` to match r00-r99 and the count to hopefully dodge normal torrents w/ included subs in `.rar` as an extra.
