### ISSUE TITLE
feat: Remove by number of seeders

### ISSUE THREAD

**Issue by brettpetch** [l3uddz/tqm#52]
Hi there,

First off, love the project. Wondering if you might consider adding a removal condition from the number of current seeders/leechers reported by the tracker on a torrent. This would allow people to ensure that if they are one of the last ones seeding a file that it could continue to be seeded, while more popular files with a healthy amount of seeders will eventually be removed..

Thanks

**Comment by saltydk** [comment]
Did you actually check if it wasn't already possible? As far as I am aware both deluge and qbt already expose those.

**Comment by saltydk** [comment]
Specifically https://github.com/l3uddz/tqm/blob/79ef524982946dd1ecf05cfa6cd422d02cd75661/client/qbittorrent.go#L176 and https://github.com/l3uddz/tqm/blob/79ef524982946dd1ecf05cfa6cd422d02cd75661/client/deluge.go#L180
